language: php
php:
  - '5.6'
  - '7.0'
  - hhvm

sudo: true

install:
  - composer install --prefer-dist --no-interaction

script: vendor/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
